apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployname }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "colors-db.selectorLabels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "colors-db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "colors-db.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.dbrepo.name }}:{{ .Values.dbrepo.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - mountPath: /data/db
          name: mysql-volume
        ports:
        - name: mysql-db
          containerPort: {{ .Values.dbservice.port }}
          protocol: TCP
        env:
        - name: DBUSER
          valueFrom:
            configMapKeyRef:
              name: webappinfo
              key: dbuser        
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbpwd
              key: dbpwd
      imagePullSecrets:
      - name: ecr-cred
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-pvc