apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dbrootpwd
  namespace: final
spec:
  encryptedData:
    dbrootpwd: AgB+rcVPs+ZYxnHMCoafsLxpIRdfGuFTAgSMPZoqC9V2Wc3lm0GU682bDVMK89ICkfcEYdZ9YYsDVoRttSoyBSMYHoQEkrUTDLnyatMCJnCiA6Mg2NaC5Ha34mkSPDnbXyAhvlbfRhPw8RtwIlJmArFju7xahXeZ5d+tJbn4RmIsGpc5oXnUxfH31XfLomUJlvQKz98lH3IAoj2B9P7IiTXyPIkA1i183KVPSJ8Eh59/Uq1VwZJfg/tj6ajSAuQ+b4gLN/nQ8/koMkqi2KhmMIk7bV5PM5hj9F9ORM7teI7eTrBZtLnhvT2mg8ksX2mi5/sVnYwZ7demMiW0fplu6OECL7LYdv+xuQixLrFdaergtwMTk4JzM6LbrVTMABPoLkEAISTPmm7SaqFZshUD2nlJ1wuBYO+PAjOxFj9u2SeU61yKnMLgPEm0cHRLygoL5msKrK+5TGd+QhzlPg1799gAd31aQZho80ZEbBW2pqRl17UWMUEkJcCh4tmDXpPIcJU9qTaLTx0Ao0Wt2QHEFipoF8O1IbCziFCJsbpmuGmEfPPYrBXEVnfjXl+BbtMQMvGdeaHYnCohhhdRzWKqdJ/9hrRnmyK8GfkFHp5UPIPWWxpW9ybGnYC1fH11BWOFi/qnHAHtsLVCINCFGsInigY/JRRG6AiYS/JUwSRCkgri5jzEWEhchMkInToi4RvfmcOJLQFvUY2CSAURaQ==
  template:
    metadata:
      creationTimestamp: null
      name: dbrootpwd
      namespace: final

