---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thelounge
  namespace: default
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: thelounge
  chart:
    repository: https://halkeye.github.io/helm-charts/
    version: 4.3.0
  values:
    ingress:
      enabled: true
      hosts:
        - lol.local