apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: thelounge
  namespace: default
spec:
  interval: 1m
  url: https://halkeye.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thelounge
  namespace: default
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  interval: 5m
  chart:
    spec:
      chart: thelounge
      sourceRef:
        kind: HelmRepository
        name: thelounge
      version: 4.3.0
  values:
    ingress:
      enabled: true
      hosts:
        - lol.local