---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: charts
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: charts
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./charts
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system