apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: colorsapp
  namespace: color-fe
spec:
  interval: 1m
  url: https://github.com/KSBolton/k8s-devops-appdeploy-eks
  ref:
    branch: flux-trial
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: colorsapp
  namespace: color-fe
spec:
  interval: 1m
  releaseName: colorsapp
  chart:
    spec:
      chart: charts/colors-app
      sourceRef:
        kind: GitRepository
        name: colorsapp