apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployname }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "colors-app.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.appservice.type }}
  selector:
      app: employees
  ports:
  - name: ext30000
    port: {{ .Values.appservice.port }}
    targetPort: {{ .Values.appservice.targetPort }}
    protocol: TCP
    nodePort: {{ .Values.appservice.nodePort }}