apiVersion: v1
kind: ConfigMap
metadata:
  name: webappinfo
  namespace: {{ .Values.namespace }}
data:
  bgimage: "https://thumbs.dreamstime.com/b/spring-summer-season-abstract-nature-background-grass-blue-sky-back-49716369.jpg"
  ournames: "Islamiyat Osuolale, Kamaal Bolton, Naveendran Wijeyasekaran, Oluwole Amusan, Superman, Thor"
  dbuser: "dbadmin"