apiVersion: v1
kind: ConfigMap
metadata:
  name: webappinfo
  namespace: {{ .Values.namespace }}
data:
  bgimage: "s3://clo835bgimg/bg10.jpg"
  ournames: "Islamiyat Osuolale, Kamaal Bolton, Naveendran Wijeyasekaran, Oluwole Amusan"
  dbuser: "dbadmin"