apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
 name: hpa
 namespace: {{ .Values.namespace }}
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: {{ .Values.deployname }}
 minReplicas: 1
 maxReplicas: 10
 metrics:
 - type: Resource
   resource:
    name: cpu
    target:
     type: Utilization
     averageUtilization: 60
 #targetCPUUtilizationPercentage: 80
