kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding
  namespace: final2
subjects:
- kind: ServiceAccount
  name: clo835
  apiGroup: ""
roleRef:
  kind: Role
  name: pod-writer
  apiGroup: rbac.authorization.k8s.io